version: '3.6'

services:

  engine:
    container_name: 'flask-starting'
    build:
      context: ./
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - FLASK_APP=manage
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://amazingUser:@amazingPassword!!@engine-db:5432/flask_starting
      - DATABASE_TEST_URL=postgres://amazingUser:@amazingPassword!!@engine-db:5432/flask_starting_test
    depends_on:
      - engine-db

  engine-db:
    container_name: 'flask-starting-db'
    build:
      context: services/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=amazingUser
      - POSTGRES_PASSWORD=@amazingPassword!!

  nginx:
    container_name: 'flask-starting-nginx'
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - engine
